from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    ProductListView, AddToCartView, CartListView, PlaceOrderView, UserOrderListView,
    AdminProductViewSet, AdminCartViewSet, AdminOrderViewSet
)

router = DefaultRouter()
# Router registrations restored
router.register('admin/products', AdminProductViewSet, basename='admin-product')
router.register('admin/carts', AdminCartViewSet, basename='admin-cart')
router.register('admin/orders', AdminOrderViewSet, basename='admin-order')

# Restoring the main urlpatterns list
urlpatterns = [
    # Authenticated users paths restored
    path('products/', ProductListView.as_view(), name='products'),
    path('cart/add/', AddToCartView.as_view(), name='add-to-cart'),
    path('cart/', CartListView.as_view(), name='cart'),
    path('order/place/', PlaceOrderView.as_view(), name='place-order'),
    path('orders/', UserOrderListView.as_view(), name='user-orders'),

    # Admin: Include the URLs generated by the router restored
    path('admin-api/', include(router.urls)),
]

# Note: The duplicate definition of urlpatterns from your previous file has been removed,
# leaving only the correct, restored list above.
