# In products/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    ProductListView, AddToCartView, CartListView, PlaceOrderView, UserOrderListView,
    AdminProductViewSet, AdminCartViewSet, AdminOrderViewSet
)

router = DefaultRouter()
# CORRECTION: Added explicit basename for clarity and safety
router.register('admin/products', AdminProductViewSet, basename='admin-product')
router.register('admin/carts', AdminCartViewSet, basename='admin-cart')
router.register('admin/orders', AdminOrderViewSet, basename='admin-order')

urlpatterns = [
    # Authenticated users
    path('products/', ProductListView.as_view(), name='products'),
    path('cart/add/', AddToCartView.as_view(), name='add-to-cart'),
    path('cart/', CartListView.as_view(), name='cart'),
    path('order/place/', PlaceOrderView.as_view(), name='place-order'),
    path('orders/', UserOrderListView.as_view(), name='user-orders'),

    # Admin: Include the URLs generated by the router
    # Note: The URL is 'admin-api/' which will prefix the ViewSet paths.
    path('admin-api/', include(router.urls)),
]


urlpatterns = [
    # Authenticated users
    path('products/', ProductListView.as_view(), name='products'),
    path('cart/add/', AddToCartView.as_view(), name='add-to-cart'),
    path('cart/', CartListView.as_view(), name='cart'),
    path('order/place/', PlaceOrderView.as_view(), name='place-order'),
    path('orders/', UserOrderListView.as_view(), name='user-orders'),

    # Admin
    path('admin-api/', include(router.urls)),
]
